apiVersion: 2019-12-01
location: northeurope
name: SQLAppGroup
properties:
  containers: 
  - name: db
    properties:
      image: springbootacz.azurecr.io/appsqlimage:latest
      resources:
        requests:
          cpu: 1
          memoryInGb: 1.5
      ports:
      - port: 3306
  - name: web
    properties:
      image: springbootacz.azurecr.io/containerapp:latest
      resources:
        requests:
          cpu: 1
          memoryInGb: 1.5
      ports:
      - port: 8080        
  osType: Linux
  ipAddress:
    type: Public
    ports:
    - protocol: tcp
      port: 8080
  imageRegistryCredentials:
    - server: springbootacz.azurecr.io
      username: springbootacz
      password: OaVNe79ALkaxTwWXCXW7cDqBPyTnAyALA2QSlatDMK+ACRBZqPs9
type: Microsoft.ContainerInstance/containerGroups